name: Create and upload artifacts

on:
    [push]
    #  release:
    #    types: [released]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-binaries:
    strategy:
      matrix:
        target:
          - { runner: "macos-latest",   arch: "x86_64-apple-darwin" }
          - { runner: "macos-latest",   arch: "aarch64-apple-darwin" }
          - { runner: "windows-2022",   arch: "x86_64-pc-windows-msvc" }
          - { runner: "ubuntu-latest",  arch: "x86_64-unknown-linux-gnu" }
          - { runner: "ubuntu-latest",  arch: "x86_64-unknown-linux-musl" }

    runs-on: ${{ matrix.target.runner }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install musl-tools (MUSL)
        if: ${{ startsWith(matrix.target.runner, 'ubuntu') && matrix.target.arch == 'x86_64-unknown-linux-musl' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install latest Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target.arch }}

      - name: Build binary using cross (Linux)
        if: ${{ startsWith(matrix.target.runner, 'ubuntu') }}
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          sudo systemctl start docker || true
          cross build --release --target ${{ matrix.target.arch }}
          cp target/${{ matrix.target.arch }}/release/wiring_rs wiring-${{ matrix.target.arch }}

      - name: Build binary using cargo (macOS)
        if: ${{ startsWith(matrix.target.runner, 'macos') }}
        run: |
          cargo build --release --target ${{ matrix.target.arch }}
          cp target/${{ matrix.target.arch }}/release/wiring_rs wiring-${{ matrix.target.arch }}

      - name: Build binary using cargo (Windows)
        if: ${{ matrix.target.runner == 'windows-2022' }}
        run: |
          cargo build --release --target ${{ matrix.target.arch }}
          cp target\${{ matrix.target.arch }}\release\wiring_rs.exe wiring-${{ matrix.target.arch }}

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.arch }}-bin
          path: wiring-${{ matrix.target.arch }}
          if-no-files-found: error
